version: "3.9"

services:
  backend:
    image: node:18
    container_name: quorvia_backend
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Mount the root directory to the container
    ports:
      - "48765:3000" # Expose backend service on port 48765
    environment:
      NODE_ENV: development
      POSTGRES_URL: postgres://quorvia_user:quorvia_password@postgres:5432/quorvia_db
      REDIS_HOST: redis
      REDIS_PORT: 63791
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 587
      SMTP_USER: your_smtp_username
      SMTP_PASS: your_smtp_password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["sh", "-c", "npm install && npm run start:backend"]

  frontend:
    image: node:18
    container_name: quorvia_frontend
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Mount the root directory to the container
    ports:
      - "48766:3001" # Expose frontend service on port 48766
    command: ["sh", "-c", "npm install && npm run start:frontend"]

  postgres:
    image: postgres:15
    container_name: quorvia_postgres
    ports:
      - "48767:5432" # Expose PostgreSQL service on port 48767
    environment:
      POSTGRES_USER: quorvia_user
      POSTGRES_PASSWORD: quorvia_password
      POSTGRES_DB: quorvia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Automatically create `quorvia_db` if not present
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quorvia_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: quorvia_redis
    ports:
      - "63791:6379" # Expose Redis service on port 63791
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Persistent data for PostgreSQL
  redis_data: # Persistent data for Redis
