version: "3.9"

services:
  backend:
    image: node:18
    container_name: quorvia_backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "48765:3000"
    environment:
      NODE_ENV: development
      POSTGRES_URL: postgres://quorvia_user:quorvia_password@postgres:5432/quorvia_user
      REDIS_HOST: redis
      REDIS_PORT: 63791
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 587
      SMTP_USER: your_smtp_username
      SMTP_PASS: your_smtp_password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["sh", "-c", "npm install && npm run start:backend"]

  frontend:
    image: node:18
    container_name: quorvia_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "48766:3001"
    command: ["sh", "-c", "npm install && npm run start:frontend"]

  postgres:
    image: postgres:15
    container_name: quorvia_postgres
    ports:
      - "48767:5432"
    environment:
      POSTGRES_USER: quorvia_user
      POSTGRES_PASSWORD: quorvia_password
      POSTGRES_DB: quorvia_user
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quorvia_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: quorvia_redis
    ports:
      - "63791:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
